if(EXISTS "/home/jorge/hyperloop/pruebaDMA3/deps/ST-LIB/Tests/st-lib-test[1]_tests.cmake")
  include("/home/jorge/hyperloop/pruebaDMA3/deps/ST-LIB/Tests/st-lib-test[1]_tests.cmake")
else()
  add_test(st-lib-test_NOT_BUILT st-lib-test_NOT_BUILT)
endif()
